#! /usr/bin/bash

# Debug level per module
DEBUG_LEVEL=3
export DEBUG_OTTER=$DEBUG_LEVEL
export DEBUG_DATATYPES=$DEBUG_LEVEL
export DEBUG_TRACE=$DEBUG_LEVEL

# Dynamic array defaults
export OTTER_DEFAULT_ARRAY_LENGTH=100
export OTTER_DEFAULT_ARRAY_INCREMENT=500
