#! /usr/bin/bash

export DEBUG_OTTER=3
export DEBUG_OTT=0
export DEBUG_ODT=0

export OTTER_DEFAULT_TASK_CHILDREN=1000
export OTT_DEFAULT_ROOT_CHILDREN=1000
export ODT_DEFAULT_ARRAY_LENGTH=100
export ODT_DEFAULT_ARRAY_INCREMENT=500
