#! /usr/bin/bash

# Debug level per module
DEBUG_ALL=3
export DEBUG_OTTER=$DEBUG_ALL
export DEBUG_OTT=$DEBUG_ALL
export DEBUG_ODT=$DEBUG_ALL

# Some handy defaults
export OTTER_DEFAULT_TASK_CHILDREN=1000
export OTT_DEFAULT_ROOT_CHILDREN=1000
export ODT_DEFAULT_ARRAY_LENGTH=100
export ODT_DEFAULT_ARRAY_INCREMENT=500
