name: 'Set up an Intel oneAPI installation'
description: 'Set up an Intel oneAPI installation with a given version and install location'

inputs:
  install_root:
    description: "The install location for oneAPI"
    required: true
  version:
    description: "The oneAPI version to use"
    required: true
outputs:
  source:
    description: "The script to source to activate the installation"
    value: ${{ steps.declare.outputs.source }}


runs:
  using: "composite"
  steps:

    - name: Set installation path
      id: declare
      shell: bash
      run: |
        export GITHUB_ENV GITHUB_OUTPUTS
        echo "ver=${{ inputs.version }}" | tee -a "$GITHUB_ENV"
        echo "path=${{ inputs.install_root }}/${{ inputs.version }}" | tee -a "$GITHUB_ENV"
        echo "source=${{ inputs.install_root }}/${{ inputs.version }}/setvars.sh" | tee -a "$GITHUB_OUTPUTS"

    - name: Check for cached installation
      id: check-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.path }}
        key: ${{ runner.OS }}-intel-cache-${{ env.path }}

    - name: Install intel on cache miss
      if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        INTEL_URL=$(sed -n "s/^${{ env.ver }}@\(.*\)/\1/p" ./.github/ci/static/intel-urls)
        if [[ -z "$INTEL_URL" ]]; then
          echo "invalid intel version: ${{ env.ver }}"
          exit 1
        fi
        printf "Downloading intel installer ${{ env.ver }} from ${INTEL_URL}\n"
        wget --no-verbose "${INTEL_URL}" -O install.sh
        sh install.sh -a --action install --components intel.oneapi.lin.dpcpp-cpp-compiler \
          --install-dir '${{ env.path }}'' --silent --cli --eula accept
