name: Build Otter

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      os:
        required: true
        type: string
      otf2_version:
        required: true
        type: string

env:
  otf2_root: /opt/deps/otf2
  intel_root: /opt/intel
  intel_version: '2025.1'

jobs:

  build-otter:
    name: Build Otter
    runs-on: ${{ inputs.os }}
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: setup otf2
        uses: ./.github/actions/setup-otf2
        with:
          install_root: ${{ env.otf2_root }}
          version: ${{ inputs.otf2_version }}
      - if: ${{ inputs.toolchain == 'intel' }}
        name: setup intel
        uses: ./.github/actions/setup-intel
        with:
          install_root: ${{ env.intel_root }}
          version: ${{ env.intel_version }}
      - if: ${{ inputs.toolchain == 'intel' }}
        name: load intel
        run: |
          source ${{ env.intel_root }}/${{ env.intel_version }}/setvars.sh
      - name: build otter
        uses: ./.github/actions/build-otter
        with:
          otf2_root: ${{ env.otf2_root }}
          otf2_version: ${{ inputs.otf2_version }}
          cc: ${{ inputs.toolchain == 'gcc' && 'gcc' || inputs.toolchain == 'clang' && 'clang' || inputs.toolchain == 'intel' && 'icx' }}
          cxx: ${{ inputs.toolchain == 'gcc' && 'g++' || inputs.toolchain == 'clang' && 'clang++' || inputs.toolchain == 'intel' && 'icpx' }}
