name: Build Otter with various compilers and OF2 versions

on:
  push:
    branches: ["dev"]

jobs:

  build:
    name: Build Otter with gcc/clang/intel
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        otf2_version: ["2.3", "3.0"]
        toolchain: ["gcc", "clang", "intel"]
    uses: ./.github/workflows/build-otter.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      os: ${{ matrix.os }}
      otf2_version: ${{ matrix.otf2_version }}
